/*
 * AfeSim_Device_Cfg.h
 *
 *  Created on: 2024Äê2ÔÂ20ÈÕ
 *      Author: Administrator
 */

#ifndef SRC_BSW_BQ79XXX_DRIVER_AFESIM_DEVICE_CFG_H_
#define SRC_BSW_BQ79XXX_DRIVER_AFESIM_DEVICE_CFG_H_

#define AFESIM_SIMULEVEL_BASICAL		0
#define AFESIM_SIMULEVEL_LOGICAL		1
#define AFESIM_SIMULEVEL_PHYSICAL		2
#define AFESIM_SIMULEVEL				AFESIM_SIMULEVEL_LOGICAL

#ifndef AFESIM_USE_BQ79616
	#ifndef AFESIM_USE_BQ79718
	#define AFESIM_USE_BQ79718
	#endif
#endif

#ifndef AFESIM_USE_BQ79718
	#ifndef AFESIM_USE_BQ79616
	#define AFESIM_USE_BQ79616
	#endif
#endif

#define AFESIM_MAX_AFE_NUM			15
#define AFESIM_MAX_REG_NUM			0x3000
#define AFESIM_MAX_DEVICE_NUM		(AFESIM_MAX_AFE_NUM + 1)
#define AFESIM_MAX_CELL_NUM			18
#define AFESIM_MAX_VCPIN_NUM		(AFESIM_MAX_CELL_NUM + 1)
#define AFESIM_MAX_CBPIN_NUM		(AFESIM_MAX_CELL_NUM + 1)
#define AFESIM_MAX_GPIO_NUM			11
#define AFESIM_MAX_MT_NUM			6
#define AFESIM_MAX_BT_NUM			2
#define AFESIM_MAX_DT_NUM			2
#define AFESIM_MAX_ST_NUM			2

#endif /* SRC_BSW_BQ79XXX_DRIVER_AFESIM_DEVICE_CFG_H_ */
